/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package condominio.frontend;
import condominio.Condominio;
import condominio.Reuniao;
import condominio.Sistema;
import condominio.exceptions.DadosJaExistentes;
import javax.swing.JOptionPane;
/**
 *
 * @author teste
 */
public class AdicionarReuniao extends javax.swing.JFrame {
private Sistema s;
    /**
     * Creates new form AdicionarReuniao
     */
    public AdicionarReuniao(Sistema s) {
        initComponents();
        this.s=s;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tipoReuniao = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        idcondominioReuniao = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        diaReuniao = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        mesReuniao = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        buttonVoltar = new javax.swing.JButton();
        buttonLimpar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        idReuniao = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Adicionar Reunião");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setText("Tipo:");

        tipoReuniao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoReuniaoActionPerformed(evt);
            }
        });

        jLabel2.setText("ID Condomínio:");

        idcondominioReuniao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idcondominioReuniaoActionPerformed(evt);
            }
        });

        jLabel3.setText("Dia:");

        diaReuniao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diaReuniaoActionPerformed(evt);
            }
        });

        jLabel4.setText("Mês:");

        jButton1.setText("Adicionar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        buttonVoltar.setText("Voltar");
        buttonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVoltarActionPerformed(evt);
            }
        });

        buttonLimpar.setText("Limpar");
        buttonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLimparActionPerformed(evt);
            }
        });

        jLabel5.setText("ID Reunião");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonVoltar)
                .addGap(19, 19, 19))
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(idReuniao))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(idcondominioReuniao, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tipoReuniao))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(diaReuniao)
                            .addComponent(mesReuniao)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonLimpar)))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idReuniao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tipoReuniao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(idcondominioReuniao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(diaReuniao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mesReuniao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(buttonLimpar))
                .addGap(18, 18, 18)
                .addComponent(buttonVoltar)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
         setDefaultCloseOperation(MenuReunioes.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_formWindowClosing

    private void tipoReuniaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoReuniaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoReuniaoActionPerformed

    private void diaReuniaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diaReuniaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diaReuniaoActionPerformed

    private void buttonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVoltarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_buttonVoltarActionPerformed

    private void idcondominioReuniaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idcondominioReuniaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idcondominioReuniaoActionPerformed

    private void buttonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLimparActionPerformed
        // TODO add your handling code here:
        tipoReuniao.setText("");
        idcondominioReuniao.setText("");
        diaReuniao.setText("");
        mesReuniao.setText("");
    }//GEN-LAST:event_buttonLimparActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      try {
        int id= Integer.parseInt(idReuniao.getText());   
        int IDC= Integer.parseInt(idcondominioReuniao.getText());
        int diaR= Integer.parseInt(diaReuniao.getText());
        String tipo = new String (tipoReuniao.getText());
        String mesR = new String (mesReuniao.getText());
        try {
        
        if (s.getListaReuniao().existeReuniao(id) ) 
            for(int z=0; z < s.getListaCondominios().tamanho();z++) {  
            Condominio c = s.getListaCondominios().BuscarCond(z);
            if (c.getID()==IDC) {
            
        Reuniao r = new Reuniao (id,tipo,IDC,diaR,mesR);
        s.getListaReuniao().addReuniao(r);
            }
            }
       
        
        } catch (DadosJaExistentes e) {
                JOptionPane.showMessageDialog(null, e.getMessage(), "ERRO", JOptionPane.ERROR_MESSAGE);
    
        }

        
        if (s.getListaReuniao().existeReuniao(id) ) {     //adiciona nova reunião
        Reuniao r = new Reuniao (id,tipo,IDC,diaR,mesR);
        s.getListaReuniao().addReuniao(r);
        
        }
        
        
        } catch (DadosJaExistentes e) {
                JOptionPane.showMessageDialog(null, e.getMessage(), "ERRO", JOptionPane.ERROR_MESSAGE);
    
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonLimpar;
    private javax.swing.JButton buttonVoltar;
    private javax.swing.JTextField diaReuniao;
    private javax.swing.JTextField idReuniao;
    private javax.swing.JTextField idcondominioReuniao;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField mesReuniao;
    private javax.swing.JTextField tipoReuniao;
    // End of variables declaration//GEN-END:variables
}
