/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package condominio.frontend;
import condominio.Sistema;

/**
 *
 * @author Miguel
 */
public class MenuManutencao extends javax.swing.JFrame {
   private Sistema s;
    /**
     * Creates new form MenuManutencao
     */
    public MenuManutencao(Sistema s) {
        initComponents();
        this.s=s;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        verOrcamentos = new javax.swing.JButton();
        addOrcamento = new javax.swing.JButton();
        addOrcamento1 = new javax.swing.JButton();
        verOrcamentos1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        verOrcamentos.setText("Procura Colaboradores");
        verOrcamentos.setMaximumSize(new java.awt.Dimension(139, 23));
        verOrcamentos.setMinimumSize(new java.awt.Dimension(139, 23));
        verOrcamentos.setPreferredSize(new java.awt.Dimension(139, 23));
        verOrcamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verOrcamentosActionPerformed(evt);
            }
        });

        addOrcamento.setText("Alterar Data");
        addOrcamento.setMaximumSize(new java.awt.Dimension(139, 23));
        addOrcamento.setMinimumSize(new java.awt.Dimension(139, 23));
        addOrcamento.setPreferredSize(new java.awt.Dimension(139, 23));
        addOrcamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addOrcamentoActionPerformed(evt);
            }
        });

        addOrcamento1.setText("Ver Manutenções");
        addOrcamento1.setMaximumSize(new java.awt.Dimension(139, 23));
        addOrcamento1.setMinimumSize(new java.awt.Dimension(139, 23));
        addOrcamento1.setPreferredSize(new java.awt.Dimension(139, 23));
        addOrcamento1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addOrcamento1ActionPerformed(evt);
            }
        });

        verOrcamentos1.setText("Adiconar Manutenção");
        verOrcamentos1.setMaximumSize(new java.awt.Dimension(139, 23));
        verOrcamentos1.setMinimumSize(new java.awt.Dimension(139, 23));
        verOrcamentos1.setPreferredSize(new java.awt.Dimension(139, 23));
        verOrcamentos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verOrcamentos1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(verOrcamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addOrcamento, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addOrcamento1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(verOrcamentos1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(79, Short.MAX_VALUE)
                .addComponent(verOrcamentos1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(addOrcamento, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(addOrcamento1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(verOrcamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void verOrcamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verOrcamentosActionPerformed
        // TODO add your handling code here:
      ProcuraColaboradores a1 = new ProcuraColaboradores(s);
        a1.setVisible(true);
    }//GEN-LAST:event_verOrcamentosActionPerformed

    private void addOrcamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addOrcamentoActionPerformed
        // TODO add your handling code here:
        DataManutencao a2 = new DataManutencao(s);
        a2.setVisible(true);
    }//GEN-LAST:event_addOrcamentoActionPerformed

    private void addOrcamento1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addOrcamento1ActionPerformed
        // TODO add your handling code here:
        ListagemManutencoes a3 = new ListagemManutencoes(s);
        a3.setVisible(true);
    }//GEN-LAST:event_addOrcamento1ActionPerformed

    private void verOrcamentos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verOrcamentos1ActionPerformed
        // TODO add your handling code here:
         AdicionarManutencao a = new AdicionarManutencao(s);
       a.setVisible(true);
        
    }//GEN-LAST:event_verOrcamentos1ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        setDefaultCloseOperation(MenuCondomino.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_formWindowClosing

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addOrcamento;
    private javax.swing.JButton addOrcamento1;
    private javax.swing.JButton verOrcamentos;
    private javax.swing.JButton verOrcamentos1;
    // End of variables declaration//GEN-END:variables
}
