/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package condominio.frontend;

import condominio.Sistema;
/**
 *
 * @author Utilizador
 */
public class MenuOrcamento extends javax.swing.JFrame {
private Sistema s;

    public MenuOrcamento(Sistema s){
        initComponents();
        this.s=s;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        verOrcamentos = new javax.swing.JButton();
        addOrcamento = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Orçamento");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        verOrcamentos.setText("Ver Orçamentos");
        verOrcamentos.setMaximumSize(new java.awt.Dimension(139, 23));
        verOrcamentos.setMinimumSize(new java.awt.Dimension(139, 23));
        verOrcamentos.setPreferredSize(new java.awt.Dimension(139, 23));
        verOrcamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verOrcamentosActionPerformed(evt);
            }
        });

        addOrcamento.setText("Adicionar Orçamentos");
        addOrcamento.setMaximumSize(new java.awt.Dimension(139, 23));
        addOrcamento.setMinimumSize(new java.awt.Dimension(139, 23));
        addOrcamento.setPreferredSize(new java.awt.Dimension(139, 23));
        addOrcamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addOrcamentoActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/condominio/frontend/Imagens/orcamento_menu.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(77, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(addOrcamento, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(verOrcamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(74, 74, 74))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(123, 123, 123))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(46, 46, 46)
                .addComponent(addOrcamento, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(verOrcamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        setDefaultCloseOperation(MenuCondomino.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_formWindowClosing

    private void addOrcamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addOrcamentoActionPerformed
        AdicionarOrçamento a=new AdicionarOrçamento(s);
        a.setVisible(true);
    }//GEN-LAST:event_addOrcamentoActionPerformed

    private void verOrcamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verOrcamentosActionPerformed
        ListagemOrçamentos l=new ListagemOrçamentos(s);
        l.setVisible(true);
    }//GEN-LAST:event_verOrcamentosActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addOrcamento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton verOrcamentos;
    // End of variables declaration//GEN-END:variables
}
