/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package condominio.frontend;
import condominio.Sistema;



/**
 *
 * @author migas
 */
public class MenuInicial extends javax.swing.JFrame {
    
    private Sistema s;
     /**
     * Creates new form MenuInicial
     */
    public MenuInicial(Sistema s) {
        initComponents();
        this.s=s;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btncondominio = new javax.swing.JButton();
        btncondomino = new javax.swing.JButton();
        bttnorcamento = new javax.swing.JButton();
        btnmanutencoes = new javax.swing.JButton();
        bttnreunioes = new javax.swing.JButton();
        bttnpagamentos = new javax.swing.JButton();
        bttnsair = new javax.swing.JButton();
        btncolaboradores = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Inical");
        setResizable(false);

        btncondominio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/condominio/frontend/Imagens/Condominio_icon.png"))); // NOI18N
        btncondominio.setText("Condomínios");
        btncondominio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncondominioActionPerformed(evt);
            }
        });

        btncondomino.setIcon(new javax.swing.ImageIcon(getClass().getResource("/condominio/frontend/Imagens/Condómino_icon.png"))); // NOI18N
        btncondomino.setText("Condominos");
        btncondomino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncondominoActionPerformed(evt);
            }
        });

        bttnorcamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/condominio/frontend/Imagens/orcamento_icon.png"))); // NOI18N
        bttnorcamento.setText("Orçamentos");
        bttnorcamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnorcamentoActionPerformed(evt);
            }
        });

        btnmanutencoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/condominio/frontend/Imagens/Manutencao_icon.png"))); // NOI18N
        btnmanutencoes.setText("Manutenções");
        btnmanutencoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmanutencoesActionPerformed(evt);
            }
        });

        bttnreunioes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/condominio/frontend/Imagens/reuniao_icon.png"))); // NOI18N
        bttnreunioes.setText("Reuniões");
        bttnreunioes.setMaximumSize(new java.awt.Dimension(97, 23));
        bttnreunioes.setMinimumSize(new java.awt.Dimension(97, 23));
        bttnreunioes.setPreferredSize(new java.awt.Dimension(97, 23));
        bttnreunioes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnreunioesActionPerformed(evt);
            }
        });

        bttnpagamentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/condominio/frontend/Imagens/dollar_icon.png"))); // NOI18N
        bttnpagamentos.setText("Pagamentos");
        bttnpagamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnpagamentosActionPerformed(evt);
            }
        });

        bttnsair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/condominio/frontend/Imagens/exit_icon.png"))); // NOI18N
        bttnsair.setText("Sair");
        bttnsair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnsairActionPerformed(evt);
            }
        });

        btncolaboradores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/condominio/frontend/Imagens/Funcionario_icon.png"))); // NOI18N
        btncolaboradores.setText("Colaboradores");
        btncolaboradores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncolaboradoresActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/condominio/frontend/Imagens/logo.png"))); // NOI18N

        jButton1.setText("Estatisticas");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bttnpagamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bttnreunioes, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnmanutencoes, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bttnsair, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btncondominio, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btncondomino, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btncolaboradores, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bttnorcamento, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btncondominio, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncondomino, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncolaboradores, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttnorcamento, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttnpagamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttnreunioes, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnmanutencoes, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttnsair, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncondominioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncondominioActionPerformed
        // TODO add your handling code here:
        MenuCondominios c1 = new MenuCondominios(s);
        c1.setLocationRelativeTo(null);
        c1.setVisible(true);
    }//GEN-LAST:event_btncondominioActionPerformed

    private void btncondominoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncondominoActionPerformed
        MenuCondomino c2=new MenuCondomino(s);
        c2.setLocationRelativeTo(null);
        c2.setVisible(true);
    }//GEN-LAST:event_btncondominoActionPerformed

    private void bttnsairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnsairActionPerformed
        // TODO add your handling code here:
        s.sair();
    }//GEN-LAST:event_bttnsairActionPerformed

    private void btncolaboradoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncolaboradoresActionPerformed
        // TODO add your handling code here:
        MenuColaborador c3 = new MenuColaborador(s);
        c3.setLocationRelativeTo(null);
        c3.setVisible(true);
        
    }//GEN-LAST:event_btncolaboradoresActionPerformed

    private void bttnorcamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnorcamentoActionPerformed
        // TODO add your handling code here:
        MenuOrcamento c4=new MenuOrcamento(s);
        c4.setLocationRelativeTo(null);
        c4.setVisible(true);
        
    }//GEN-LAST:event_bttnorcamentoActionPerformed

    private void bttnpagamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnpagamentosActionPerformed
        // TODO add your handling code here:
        MenuPagamentos c5 = new MenuPagamentos(s);
        c5.setLocationRelativeTo(null);
        c5.setVisible(true);
    }//GEN-LAST:event_bttnpagamentosActionPerformed

    private void bttnreunioesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnreunioesActionPerformed
        // TODO add your handling code here:
        MenuReunioes c6 = new MenuReunioes(s);
        c6.setLocationRelativeTo(null);
        c6.setVisible(true);
    }//GEN-LAST:event_bttnreunioesActionPerformed

    private void btnmanutencoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmanutencoesActionPerformed
        // TODO add your handling code here:
        MenuManutencao c7 = new MenuManutencao(s);
        c7.setLocationRelativeTo(null);
        c7.setVisible(true);
    }//GEN-LAST:event_btnmanutencoesActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         Estatisticas e=new Estatisticas(s);
         e.setVisible(true);
         
         
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncolaboradores;
    private javax.swing.JButton btncondominio;
    private javax.swing.JButton btncondomino;
    private javax.swing.JButton btnmanutencoes;
    private javax.swing.JButton bttnorcamento;
    private javax.swing.JButton bttnpagamentos;
    private javax.swing.JButton bttnreunioes;
    private javax.swing.JButton bttnsair;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}