/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package condominio.frontend;
import java.util.ArrayList;
import condominio.Condominio;
import condominio.Sistema;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author migas
 */
public class MenuCondominios extends javax.swing.JFrame {
 private Sistema s;
    /**
     * Creates new form Condominio
     */
    public MenuCondominios(Sistema s) {
        initComponents();
        this.s =s;
        
       
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        newcondominio = new javax.swing.JButton();
        editcondominio = new javax.swing.JButton();
        listcondominios = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        listcondominios1 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Área", "CodigoPostal", "Localização"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Condomínios");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        newcondominio.setText("Adicionar Condomínio");
        newcondominio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newcondominioActionPerformed(evt);
            }
        });

        editcondominio.setText("Editar Condomínio");
        editcondominio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editcondominioActionPerformed(evt);
            }
        });

        listcondominios.setText("Lista de Condomínios");
        listcondominios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listcondominiosActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/condominio/frontend/Imagens/Condominio_menu.png"))); // NOI18N

        listcondominios1.setText("Fracoes");
        listcondominios1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listcondominios1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(listcondominios, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editcondominio, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(newcondominio, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(listcondominios1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jLabel1)))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addComponent(newcondominio, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(editcondominio, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(listcondominios, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(listcondominios1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newcondominioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newcondominioActionPerformed
        // TODO add your handling code here:
        AdicionarCondominio c = new AdicionarCondominio(s);
        c.setLocationRelativeTo(null);
        c.setVisible(true);  
    }//GEN-LAST:event_newcondominioActionPerformed

    private void listcondominiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listcondominiosActionPerformed
        // TODO add your handling code here:
        ListagemCondominios l = new ListagemCondominios(s);
        l.setVisible(true);
    }//GEN-LAST:event_listcondominiosActionPerformed

    private void editcondominioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editcondominioActionPerformed
        // TODO add your handling code here:
      EditarCondominio e = new EditarCondominio(s);
        e.setVisible(true);
    }//GEN-LAST:event_editcondominioActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        setDefaultCloseOperation(MenuCondomino.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_formWindowClosing

    private void listcondominios1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listcondominios1ActionPerformed
        // TODO add your handling code here:
        MenuFracoes j = new MenuFracoes (s);
        j.setVisible(true);
    }//GEN-LAST:event_listcondominios1ActionPerformed

    /**
     * @param args the command line arguments
     */
 
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton editcondominio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton listcondominios;
    private javax.swing.JButton listcondominios1;
    private javax.swing.JButton newcondominio;
    // End of variables declaration//GEN-END:variables
}
